export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_DELETE_ITEM = "CART_DELETE_ITEM";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const ADD_SHIPPING_ADDRESS = "ADD_SHIPPING_ADDRESS";
export const CLEAR_SHIPPING_ADDRESS = "CLEAR_SHIPPING_ADDRESS";
export const ADD_PAYMENT_METHOD = "ADD_PAYMENT_METHOD";
export const CLEAR_PAYMENT_METHOD = "CLEAR_PAYMENT_METHOD";
